name: mirrorchyan

on:
  workflow_dispatch:

jobs:
  mirrorchyan:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        os: [win, macos, linux]
        arch: [aarch64, x86_64]
        exclude:
          - os: win
            arch: aarch64
    steps:
      - uses: MirrorChyan/uploading-action@v1
        if: ${{ matrix.os == 'win' && github.repository_owner == 'MAA1999' }}
        with:
          filetype: latest-release
          filename: "M9A-${{ matrix.os }}-${{ matrix.arch }}-*.zip"
          mirrorchyan_rid: M9A

          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}

      - uses: MirrorChyan/uploading-action@v1
        if: ${{ matrix.os != 'win' && github.repository_owner == 'MAA1999' }}
        with:
          filetype: latest-release
          filename: "M9A-${{ matrix.os }}-${{ matrix.arch }}-*.zip"
          mirrorchyan_rid: M9A

          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}
